spring:
  application:
    name: spring-ai-alibaba-chat
  ai:
    dashscope:
      # 阿里云通义模型API Key
      api-key: ${AI_DASHSCOPE_API_KEY}  # 从环境变量获取API Key
#      chat:
#        options:
#          model: qwen-plus  # 通义千问模型: qwen-turbo, qwen-plus, qwen-max
#          temperature: 0.7  # 创造性程度 0.0-1.0
#          top-p: 0.8        # 核采样参数

# HTTP客户端超时配置
  http:
    client:
      timeout:
        connection: 30000      # 连接超时 30秒
        read: 60000           # 读取超时 60秒

# 日志配置
logging:
  level:
    com.example: DEBUG
    com.alibaba.cloud.ai: DEBUG